# Generated by Django 5.2.11 on 2026-02-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_ingredient', models.CharField(max_length=100)),
                ('sauce_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('grape', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('red', 'Красное'), ('white', 'Белое'), ('sparkling', 'Игристое')], max_length=20)),
                ('acidity', models.IntegerField()),
                ('body', models.IntegerField()),
                ('sweetness', models.IntegerField()),
            ],
        ),
    ]
