# Generated by Django 5.2.11 on 2026-03-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='country',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='acidity',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='sweetness',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='type',
        ),
        migrations.AddField(
            model_name='wine',
            name='aroma',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='food_pairing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wines/'),
        ),
        migrations.AddField(
            model_name='wine',
            name='tannin',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='wine',
            name='body',
            field=models.IntegerField(default=3),
        ),
    ]
