# Generated by Django 5.2.11 on 2026-03-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_country_wine_region_remove_wine_acidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='acidity',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='wine',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='wine',
            name='sweetness',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='wine',
            name='type',
            field=models.CharField(default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grape',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wine',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
